config/routes.rb
Rails.application.routes.draw do
  root to: "/orden_trabajos/:orden_trabajo_id", to: "orden_trabajos#index"
  resources :orden_trabajos

  get '/orden_trabajos/:id/copy', to: 'orden_trabajos#copy', as: :copy

  get 'proximo_vencer', to: 'orden_trabajos#proximo_vencer', as: :proximo_vencer
  get 'planificacion_taller', to: 'orden_trabajos#planificacion_taller', as: :planificacion_taller
  get 'planificacion_tallerPDF', to: 'orden_trabajos#planificacion_tallerPDF', as: :planificacion_tallerPDF
  get 'nueva_ot', to: 'orden_trabajos#nueva_ot', as: :nueva_ot

  # Rutas creadas para cada pantalla

  get 'listado', to: 'orden_trabajos#listado', as: :listado
  get 'offset1', to: 'orden_trabajos#offset1', as: :offset1
  get 'offset2', to: 'orden_trabajos#offset2', as: :offset2
  get 'digital', to: 'orden_trabajos#digital', as: :digital
  get 'post1', to: 'orden_trabajos#post1', as: :post1
  get 'post2', to: 'orden_trabajos#post2', as: :post2
  get 'post3', to: 'orden_trabajos#post3', as: :post3
  get 'post4', to: 'orden_trabajos#post4', as: :post4
  get 'post5', to: 'orden_trabajos#post5', as: :post5
  get 'post6', to: 'orden_trabajos#post6', as: :post6
  get 'post7', to: 'orden_trabajos#post7', as: :post7
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :orden_trabajos_imports, only: [:new, :create]
  get 'orden_trabajos_imports/new'
  get 'orden_trabajos_imports/create'
end

app/controllers/orden_trabajos_imports_controller.rb
class OrdenTrabajosImportsController < ApplicationController
  def new
  end

  def create
    if params[:file].blank?
      redirect_to orden_trabajos_imports_new_path, alert: "Debes seleccionar un archivo Excel."
      return
    end

    service = OrdenTrabajoImportService.new(params[:file])

    if service.call
      redirect_to orden_trabajos_path, notice: "Importación completada (#{service.imported_count} registros)."
    else
      redirect_to orden_trabajos_imports_new_path, alert: "Error en la importación: #{service.errors.join(', ')}"
    end
  end
end

app/views/orden_trabajos_imports/new.html.erb
<div class="container mt-5">
  <h2 class="mb-4 text-center">Importar Órdenes de Trabajo desde Excel</h2>

  <div class="card p-4 shadow-sm">
    <%= form_with url: orden_trabajos_imports_path, local: true, html: { multipart: true } do |form| %>
      <div class="form-group mb-3">
        <%= form.label :file, "Seleccionar archivo Excel (.xlsx o .xls)", class: "form-label" %>
        <%= form.file_field :file, accept: ".xls,.xlsx", class: "form-control" %>
      </div>

      <%= form.submit "Importar", class: "btn btn-primary btn-lg mt-3" %>
    <% end %>
  </div>

  <div class="alert alert-info mt-4">
    <strong>Formato esperado del Excel:</strong><br>
    trnum, trcan, trcar, clinom, papel, gramaje, colores, pliego, nomprod, fecentr, cam10, cam12, cam24
  </div>
</div>